package com.flipperdevices.core.ui.theme.composable.pallet

import androidx.compose.ui.graphics.Color

/**
 * Colors with no natural home in [com.flipperdevices.core.ui.theme.composable.pallet.generated.FlipperPalletV2].
 *
 * V2 is autogenerated (see the header comment on every file under `.pallet.generated`) from a role-based design
 * system: text/surface/action/illustration/category/icon. That covers status badges, category chrome, and on-color
 * text well — better than the legacy [com.flipperdevices.core.ui.theme.composable.FlipperPallet] did, in fact,
 * since it has 11 category slots to legacy's 5 key types.
 *
 * What V2 has no slot for is one-off illustration color for a specific widget: the NFC card visualizer, the
 * battery gauge, the MfKey32 progress highlight, the key-emulate "bubble" overlay, the infrared editor canvas,
 * the hex-keyboard / NFC-editor substrate cell. Those aren't a missing *role*, they're bespoke chrome, so they
 * don't belong inside the generated file even by hand-patching it — the next regeneration would erase them.
 *
 * This file is that carve-out. Values are carried over unchanged from the legacy pallet, which never varied these
 * by light/dark theme either (they were fixed `val`s on the data class, not constructor params fed by
 * `lightPallet`/`darkPallet`), so no visual change happens as call sites migrate onto this file.
 *
 * When a legacy field genuinely fits an existing V2 role instead, migrate the call site onto that role directly —
 * do not duplicate it here. See MIGRATION.md in this module for the field-by-field guidance.
 */
object FlipDroidPalletExtras {

    // NFC card visualizer (components/nfc, keyscreen)
    val nfcCardUid: Color = Color(0xFF8A2BE2)
    val nfcCardKeyA: Color = Color(0xFF2ED832)
    val nfcCardAccessBits: Color = Color(0xFFF63F3F)
    val nfcCardKeyB: Color = Color(0xFF589DFF)
    val nfcCardBackground: Color = Color(0xFF4A4A4A)
    val onNfcCard: Color = Color(0xFFFFFFFF)

    // Battery gauge (components/info ComposableFlipperBattery)
    val batteryRed: Color = Color(0xFFF63F3F)
    val batteryYellow: Color = Color(0xFFFECF5D)
    val batteryGreen: Color = Color(0xFF34C7A4)
    val batteryBackground: Color = Color(0xFF8D8E92)
    val batteryCharging: Color = Color(0xFF303030)

    // MfKey32 calculation highlight (components/toolstab, nfc/mfkey32)
    val calculationMfKey32: Color = Color(0xFFFF8200)
    val calculationMfKey32Background: Color = Color(0xFFFF8200).copy(alpha = 0.54f)

    // Key-emulate "bubble" overlay (components/keyemulate)
    val bubbleEmulateBackground: Color = Color(0xFFC1C1C1)
    val bubbleEmulate: Color = Color(0xFFFFFFFF)

    // Infrared editor canvas (components/infrared/editor)
    val infraredEditorDrag: Color = Color(0xFFFFFFFF).copy(alpha = 0.5f)
    val infraredEditorKeyName: Color = Color(0xFFFFFFFF)

    // Hex keyboard / NFC editor substrate cell (components/core/ui/hexkeyboard, nfceditor)
    val hexKeyboardBackground: Color = Color(0xFF616161)
    val substrateActiveCellNfcEditor: Color = Color(0xFFDFDFDF)

    // On-Flipper OLED screen tint (components/screenstreaming) — the device's own display color, not app UI
    val flipperScreenColor: Color = Color(0xFFFF8C29)
    val flipperScreenOptionsBackground: Color = Color(0xFFFF8200).copy(alpha = 0.2f)
}
